### ISSUE TITLE
Error reindexing Solr, timed out after 5001 milliseconds.

### ISSUE THREAD

**Issue by sandro-saperfare** [jeroenvermeulen/magento-solarium#106]
Hi all.
When I launch the cmd php -f ./shell/indexer.php — -reindex catalogsearch_fulltext this is the result:
Error reindexing Solr: Solr HTTP error: HTTP request failed, Operation timed out after 5001 milliseconds with 0 bytes received
How and where to increase time limit?

magento-1.9.2.1
solr-4.10.4 that works in multicore with Tomcat7.

Thanks.

**Comment by sandro-saperfare** [comment]
Sorry, I've changed the parameter Search Timeout and now the index is created without problems.

**Comment by toonvd** [comment]
No problem, just close the issue if it is fixed, thanks!
