### ISSUE TITLE
Error reindexing Solr: Solr HTTP error: HTTP request failed, Operation timed out after 5015 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by xNegma** [jeroenvermeulen/magento-solarium#46]
Having this error during indexing. 

Magento version: 1.9.0.1
Solr version: 3.6.2
General timeout set to 10000
Number of SKUs: 40k

This is my pastebin...

http://pastebin.com/bKBbSkPG

**Comment by nanobytz** [comment]
Where are the server_search_timeout and server_timeout vars found?

**Comment by toonvd** [comment]
they are system config fields in the solarium tab, search timeout and general timeout
