### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by compact722** [jeroenvermeulen/magento-solarium#51]
Hi,

I have installed your extension (which seems to have installed fine)

I can search on solr admin panel and get results, however can't get any search results in Magento?

Connection to Solr	Success	 
Ping Solr	Success	 
Check Solr version	Success	 
Inserting test entry in Solr	Success	 
Search for test entry	FAILED	 
Test Autocomplete	Success	 
Test Correction of Typos	Success	 
Test "Did You Mean..."	FAILED	 
Deleting test entry from Solr	Success

Any idea?

Thanks

**Comment by toonvd** [comment]
close due to inactivity
