### ISSUE TITLE
Show products as Autocomplete error

### ISSUE THREAD

**Issue by s2krish** [jeroenvermeulen/magento-solarium#53]
Hi, I have a Magento store that has 130k products. I install module works great. When I turn on Autocomplete, I got following error:

	a:5:{i:0;s:103:"Solr HTTP error: HTTP request failed, Operation timed out after 5000 milliseconds with 0 bytes received";i:1;s:2533:"#0 /[path_to_magento]/lib/Solarium/Core/Client/Adapter/Curl.php(123): Solarium\Core\Client\Adapter\Curl->check('', Array, Resource id #146)
	#1 /[path_to_magento]/lib/Solarium/Core/Client/Adapter/Curl.php(99): Solarium\Core\Client\Adapter\Curl->getResponse(Resource id #146, false)
	#2 /[path_to_magento]/lib/Solarium/Core/Client/Adapter/Curl.php(83): Solarium\Core\Client\Adapter\Curl->getData(Object(Solarium\Core\Client\Request), Object(Solarium\Core\Client\Endpoint))
	#3 /[path_to_magento]/lib/Solarium/Core/Client/Client.php(796): Solarium\Core\Client\Adapter\Curl->execute(Object(Solarium\Core\Client\Request), Object(Solarium\Core\Client\Endpoint))
	#4 /[path_to_magento]/lib/Solarium/Core/Client/Client.php(766): Solarium\Core\Client\Client->executeRequest(Object(Solarium\Core\Client\Request), NULL)
	#5 /[path_to_magento]/lib/Solarium/Core/Client/Client.php(879): Solarium\Core\Client\Client->execute(Object(Solarium\QueryType\Select\Query\Query), NULL)
	#6 /[path_to_magento]/app/code/community/JeroenVermeulen/Solarium/Model/Engine.php(669): Solarium\Core\Client\Client->select(Object(Solarium\QueryType\Select\Query\Query))
	#7 /[path_to_magento]/app/code/community/JeroenVermeulen/Solarium/Block/Catalogsearch/Autocomplete.php(84): JeroenVermeulen_Solarium_Model_Engine->getAutoSuggestions('1', 'gr')
	#8 /[path_to_magento]/app/code/core/Mage/CatalogSearch/Block/Autocomplete.php(42): JeroenVermeulen_Solarium_Block_Catalogsearch_Autocomplete->getSuggestData()
	#9 /[path_to_magento]/app/code/community/JeroenVermeulen/Solarium/Block/Catalogsearch/Autocomplete.php(39): Mage_CatalogSearch_Block_Autocomplete->_toHtml()
	#10 /[path_to_magento]/app/code/core/Mage/Core/Block/Abstract.php(919): JeroenVermeulen_Solarium_Block_Catalogsearch_Autocomplete->_toHtml()
	#11 /[path_to_magento]/app/code/community/JeroenVermeulen/Solarium/controllers/AjaxController.php(49): Mage_Core_Block_Abstract->toHtml()
	#12 /[path_to_magento]/app/code/core/Mage/Core/Controller/Varien/Action.php(418): JeroenVermeulen_Solarium_AjaxController->suggestAction()
	#13 /[path_to_magento]/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('suggest')
	#14 /[path_to_magento]/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
	#15 /[path_to_magento]/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
	#16 /[path_to_magento]/app/Mage.php(684): Mage_Core_Model_App->run(Array)
	#17 /[path_to_magento]/index.php(87): Mage::run('', 'store')
	#18 {main}";s:3:"url";s:28:"/solarium/ajax/suggest/?q=gr";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}ubuntu@ip-172-3

**Comment by toonvd** [comment]
close due to inactivity
