### ISSUE TITLE
SOLR Error Observation

### ISSUE THREAD

**Issue by Oreoluwa** [jeroenvermeulen/magento-solarium#55]
Hi,
I'm trying out the SOLR installation now, however my searches are not returning any information, checking my solr installation logs, I saw the following errors:

WARN
Config
You should not use LATEST as luceneMatchVersion property: if you use this setting,​ and then Solr upgrades to a newer release of Lucene,​ sizable changes may happen. If precise back compatibility is important then you should instead explicitly specify an actual Lucene version.

WARN
SolrResourceLoader
Solr loaded a deprecated plugin/analysis class [solr.XmlUpdateRequestHandler]. Please consult documentation how to replace it accordingly.

WARN
RequestHandlers
Multiple requestHandler registered to the same name: /update ignoring: org.apache.solr.handler.UpdateRequestHandler

WARN
UpdateRequestHandler
Using deprecated class: XmlUpdateRequestHandler -- replace with UpdateRequestHandler

WARN
Grouping
Query: +text:solariumselftest +text:2147483647; Elapsed time: 20Exceeded allowed search time: 5 ms.

**Comment by toonvd** [comment]
close due to inactivity

**Comment by simbus82** [comment]
I have the problem that say the core can't be created because solr.XmlUpdateRequestHandler.
I have removed "xml" so i have
<requestHandler name="/update" class="solr.UpdateRequestHandler"/> in solrconfig.xml and now i can create my cores!

**Comment by jeroenvermeulen** [comment]
Beste afzender,

Van 10 t/m 23 mei heb ik vakantie. 
Daarna zal ik uw mail bekijken.

10 t/m 15 mei: 
Voor hosting storingen kunt u bellen naar mij: +32-48.757.3220.
Voor hosting vragen kunt u mailen naar Roland: roland@magehost.pro 

16 t/m 23 mei: 
Voor hosting storingen kunt u bellen naar Roland: +31-6.51.865.409
Voor hosting vragen kunt u mailen naar Roland: roland@magehost.pro 

--------------------------------------------------------------------------------------------------------------------------------
Dear sender,

I am on holiday from the May 10 till May 23.
Afterwards I will read your email.

May 10 till 15: 
In case of a hosting incident you can call to me: +32-48.757.3220.
If you have hosting questions you can mail to Roland: roland@magehost.pro 

May 16 till 23: 
In case of a hosting incident you can call Roland: +31-6.51.865.409
If you have hosting questions you can mail to Roland: roland@magehost.pro 

Kind regards,
Jeroen Vermeulen

Jeroen Vermeulen BVBA
+32-48.757.3220
www.jeroenvermeulen.eu
