### ISSUE TITLE
Feature Request: Search CMS Pages

### ISSUE THREAD

**Issue by theycallmepepper** [jeroenvermeulen/magento-solarium#77]
Would you consider adding the option to add CMS pages to the solr index to make solarium work as a site wide search rather than product specific?  I was using another extension in conjunction with this one that offers enabling/disabling CMS pages in results and if that were an option here, I could probably eliminate that extension entirely from my store.

**Comment by theycallmepepper** [comment]
Sorry, just saw this is already in the ideas for future versions.

**Comment by toonvd** [comment]
Indeed :)
