### ISSUE TITLE
Partial search

### ISSUE THREAD

**Issue by Davelaar** [jeroenvermeulen/magento-solarium#89]
When doing a partial search no results. Probably overlooked something, but cannot find this in settings or in issues. When searching for "standaard" results do not include "zijstandaard" for example. Can this be solved or do I have to live with it? For the rest it's really awesome.

**Comment by typify** [comment]
Add 
`<filter class="solr.NGramFilterFactory" maxGramSize="25" minGramSize="3"/>`
to your schema.xml. This should be placed within the following section:
`<analyzer type="index">`

Should do the trick!

**Comment by Davelaar** [comment]
OK, it looks like this is working. But my reindex then times out on deletion of product so I have to experiment with the values

**Comment by Davelaar** [comment]
Ok close issue. Works for me on Magento 1.9.1.1 and SOLR 4.10.4 with setting: <filter class="solr.NGramFilterFactory" maxGramSize="10" minGramSize="3"/>

Last Modified:7 minutes agoNum Docs:59781Max Doc:59781Heap Memory Usage:2008232Deleted Docs:0Version:64Segment Count:1

(OK it takes ages, but it is working). Any tips how to speed the things up??)

De Solr Index is gevuld in 190.02 seconden.
Catalogus zoekindex index is vernieuwd

If no ideas to speed up I'll close this in two weeks

**Comment by toonvd** [comment]
How many products are we talking about?

**Comment by Davelaar** [comment]
I have currently 61528 products in shop.

**Comment by toonvd** [comment]
Hmz this shoudln't be a problem, are you using Tomcat or going jetty? How many attributes do you have enabled for use in quick search? You could also finetune solr settings. See: http://stackoverflow.com/questions/12328969/speed-up-solr-indexing

**Comment by Davelaar** [comment]
Ok, I think it has to do with the attributes. Right now I have only 2 additional attributes enabled for quick search and that reduced the time to 130 seconds average. I'm going to dig in Solr tuning to see if there can be made a performance boost. Kind of new to the whole Solr thing. By the way I'm on Tomcat
