### ISSUE TITLE
Umlaut character issues

### ISSUE THREAD

**Issue by snufpunk** [jeroenvermeulen/magento-solarium#91]
Umlaut characters in auto suggested product names/titles were displayed as gibberish (Magento CE 1.7.0.2, centos 6.6, solr 4.9.1, java 1.7.0_75)

the following changes in Autocomplete.php resolved the issue;

                foreach ($productCollection as $product) {
                    $rowClass = ( ++$counter ) % 2 ? 'odd' : 'even';
                    $imageUrl = Mage::helper( 'catalog/image' )->init( $product, 'thumbnail' )->resize( '50' );
                    $showName = Mage::helper( 'core/string' )->truncate( $product->getName(), 100 );
					
					/* FDS - Bad Chars Fix */
					$killChars = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $showName);
					/* FDS - Bad Chars Fix */
					
                    $html .= sprintf( '<li title="%s" class="%s" data-url="%s">',
                                      
									  /* FDS - Bad Chars Fix */
									  htmlentities($killChars),
									  //htmlentities($product->getName()),
                                      /* FDS - Bad Chars Fix */
									  
									  $rowClass,
                                      htmlentities($product->getProductUrl()) );
                    $html .= '<span class="suggestions-productimage">';
                    $html .= sprintf( '<img src="%s" />', htmlentities( $imageUrl ) );
                    $html .= '</span>';
                    $html .= '<span class="suggestions-productname">';
					
					/* FDS - Bad Chars Fix */					
                    $html .= htmlentities( $killChars );
					//$html .= htmlentities( $showName );
					/* FDS - Bad Chars Fix */
					
                    $html .= '</span>';
                    $html .= '</li>';
                }

**Comment by toonvd** [comment]
hi, you can always make a pullrequest if you want, thx!

**Comment by toonvd** [comment]
@snufpunk If you don't want to make the pullrequest I could make one myself, your choise, thx for the contribution already! :+1:

**Comment by snufpunk** [comment]
Hi,

Sorry, not really familiar with the GIT system and got lost when tried to make a pull request - go a head :-)

**Comment by toonvd** [comment]
allright, will probably add it in the weekend :)
