### ISSUE TITLE
Does this plugin offer search result page which fetches result(displaying products) from solr?

### ISSUE THREAD

**Issue by anthony-nestincubate** [jeroenvermeulen/magento-solarium#94]
When I go to the search result page, it is actually redirected to the catalog search page(the default one). So is that the actually way or does does it show results from solr.

**Comment by toonvd** [comment]
The calculation is off course made by SOLR, otherwise the extension would be useless. It would also be bad to not use core functionality and make a standalone engine while Magento provides a way to just swap out engines.

**Comment by anthony-nestincubate** [comment]
But what my question is does this plugin offer search results page where the results are fetched from solr.

**Comment by toonvd** [comment]
The results are fetched from SOLR like they would be fetched from mysql. I don't understand your point.

**Comment by anthony-nestincubate** [comment]
Well when the results of auto-suggest come from the solr but the when i hit the search button it lands to search result page(which is by default the catalaog search one in magento). Here the results are not coming from solr

**Comment by snufpunk** [comment]
Man.... The results are proccessed by Solr - and displayed on the magento search results page

**Comment by anthony-nestincubate** [comment]
in my localhost it goes to this link for search results page http://localhost/lucene/index.php/catalogsearch/result/?q=****

**Comment by anthony-nestincubate** [comment]
it shows the results even if solr is turned off

**Comment by snufpunk** [comment]
yes.... 

and this page shows the results as they are fetched from Solr (if solr extension is enabled)
if Solr extension is not enabled - you get the same page but with results from the database (normal magento functionality)

In both cases, results will be displayed on the generic magento search results page

**Comment by anthony-nestincubate** [comment]
my point is that results in the search page are not from solr irrespective of whether solr is on or off

**Comment by snufpunk** [comment]
Do a 2-3 letter partial match or search a word with a small typo when the Solr magento is enabled (for example if you are searching for "Table" input "Tabrle" in the earch field - if you are getting results - Solr is working and the results are fetched from Solr

**Comment by anthony-nestincubate** [comment]
well the results of autosuggestion are from solr...I agree..but the when i hit enter the results in the search result page are from from magento

**Comment by snufpunk** [comment]
... If you get results, after searching for a word with a typo - the results are most likely coming from Solr - not Magento as the magento search module cannot overcome even the slightest typos...

If you do get results (not suggestions) with a typo, turn Solr extension off, clear cache and perform the same typo search again - you should not get results (or at least not the same results as you got before).

**Comment by toonvd** [comment]
The results are not from Magenot... they are even corrected when you make typos, what happens here is that SOLR gets called, the calculation is made and the result is saved in the catalogsearch_result table afterwards. This gives you a fallback to get precise results even after Solr is disabled for some reason. When the catalogsearch_result table is cleared, you will see that the results are different. It would be wise to check codeflow with for example xdebug to understand this better.

**Comment by anthony-nestincubate** [comment]
well after turning off the solr and clearing the cache the result is the same....

**Comment by snufpunk** [comment]
Please read toonvd's explanation as to why.

Again, if you got results for a search term with a typo - the results are coming from Solr and the extension is working as expected.

**Comment by anthony-nestincubate** [comment]
and also my catalogsearch_result table is always empty....do u have any live example

**Comment by toonvd** [comment]
http://www.onderdelenwinkel.nl/catalogsearch/result/?q=korcher This is an example, if it does not work as I described there is probably something wrong with your setup.

**Comment by anthony-nestincubate** [comment]
fine...but what my requirement is whatever is seen in the result(the products ) page should be same for auto suggest

**Comment by toonvd** [comment]
You mean the product autocomplete? I haven't noticed a difference but will take a look. Could you rename the issue to something more relevant meanwhile? Thx!

**Comment by anthony-nestincubate** [comment]
well i have modified for implementing product autocomplete.....but i find that the result(products) displayed in the search are not from solr....

**Comment by toonvd** [comment]
The products never come from solr in any case, solr just passes the ids in all cases, the collection is fetched based on those ids.

**Comment by harish-bisht** [comment]
In my case result on catalogsearch/result/ page does not sorted correctly based on sku. How to fix this issue? Help needed.

**Comment by toonvd** [comment]
@harish-bisht please make this a seperate issue, don't go hijacking others.
